In [1]:
# se importan librerias
import pandas as pd
import numpy as np

In [5]:
# se carga el dataset
df = pd.read_csv('../data/customer_acquisition_data.csv')
df.head()

   customer_id           channel       cost  conversion_rate  revenue
0            1          referral   8.320327         0.123145     4199
1            2  paid advertising  30.450327         0.016341     3410
2            3   email marketing   5.246263         0.043822     3164
3            4      social media   9.546326         0.167592     1520
4            5          referral   8.320327         0.123145     2419

In [6]:
# se crea la columna net_value
df['net_value'] = df['revenue'] - df['cost'].round(3)
df.head()

,customer_id,channel,cost,conversion_rate,revenue,net_value
0,1,referral,8.320327,0.123145,4199,4190.680
1,2,paid advertising,30.450327,0.016341,3410,3379.550
2,3,email marketing,5.246263,0.043822,3164,3158.754
3,4,social media,9.546326,0.167592,1520,1510.454
4,5,referral,8.320327,0.123145,2419,2410.680

In [ ]:
summary = (
    df[["revenue", "net_value", "conversion_rate", "cost"]]
    .quantile([0.25, 0.5, 0.75])
    .round(3)
)

display(summary)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()