In [17]:
# importamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_csv("../data/customer_segmented.csv")
df.head()

,customer_id,channel,cost,conversion_rate,revenue,net_value,customer_segment,customer_value_score,customer_value_score_net
0,1,referral,8.320327,0.123145,4199,4190.680,High Value - Standard Efficiency,4,4
1,2,paid advertising,30.450327,0.016341,3410,3379.550,Low Value,0,0
2,3,email marketing,5.246263,0.043822,3164,3158.754,Cost Efficient - Potential Value,1,1
3,4,social media,9.546326,0.167592,1520,1510.454,Low Value,1,0
4,5,referral,8.320327,0.123145,2419,2410.680,Low Value,0,0

In [19]:
# principales estadísticas por segmento de clientes
df.groupby("customer_segment")[
    ["revenue", "net_value", "cost", "conversion_rate"]
].agg(["mean", "median", "count"])

                                      revenue                  net_value  \
                                         mean  median count         mean
customer_segment
Cost Efficient - Potential Value  2355.674699  2479.0   166  2350.428699
High Value - High Efficiency      4451.333333  4521.5    48  4446.087333
High Value - Standard Efficiency  4364.414474  4339.0   152  4347.408566
Low Value                         2182.543779  2181.0   434  2166.851032

                                                       cost                  \
                                    median count       mean    median count
customer_segment
Cost Efficient - Potential Value  2473.754   166   5.246263  5.246263   166
High Value - High Efficiency      4516.254    48   5.246263  5.246263    48
High Value - Standard Efficiency  4326.680   152  17.006234  9.546326   152
Low Value                         2168.502   434  15.693073  9.546326   434

                                 conversion_rate
                                            mean    median count
customer_segment
Cost Efficient - Potential Value        0.043822  0.043822   166
High Value - High Efficiency            0.043822  0.043822    48
High Value - Standard Efficiency        0.097130  0.123145   152
Low Value                               0.103461  0.123145   434

In [20]:
# principales estadísticas por segmento de clientes y canal
df.groupby(
    ["customer_segment", "channel"]
)[["revenue", "net_value", "cost", "conversion_rate"]].mean()

                                                       revenue    net_value  \
customer_segment                 channel
Cost Efficient - Potential Value email marketing   2355.674699  2350.428699
High Value - High Efficiency     email marketing   4451.333333  4446.087333
High Value - Standard Efficiency paid advertising  4392.912281  4362.462281
                                 referral          4369.659574  4361.339574
                                 social media      4325.437500  4315.891500
Low Value                        paid advertising  2175.182482  2144.732482
                                 referral          2276.112500  2267.792500
                                 social media      2080.627737  2071.081737

                                                        cost  conversion_rate
customer_segment                 channel
Cost Efficient - Potential Value email marketing    5.246263         0.043822
High Value - High Efficiency     email marketing    5.246263         0.043822
High Value - Standard Efficiency paid advertising  30.450327         0.016341
                                 referral           8.320327         0.123145
                                 social media       9.546326         0.167592
Low Value                        paid advertising  30.450327         0.016341
                                 referral           8.320327         0.123145
                                 social media       9.546326         0.167592

In [21]:
# tabla resumen por segmento de clientes
segment_summary = (
    df.groupby("customer_segment")
    .agg(
        customers=("customer_id", "count"),
        avg_revenue=("revenue", "mean"),
        avg_net_value=("net_value", "mean"),
        avg_cost=("cost", "mean"),
        avg_conversion_rate=("conversion_rate", "mean")
    )
    .reset_index()
)

segment_summary

,customer_segment,customers,avg_revenue,avg_net_value,avg_cost,avg_conversion_rate
0,Cost Efficient - Potential Value,166,2355.674699,2350.428699,5.246263,0.043822
1,High Value - High Efficiency,48,4451.333333,4446.087333,5.246263,0.043822
2,High Value - Standard Efficiency,152,4364.414474,4347.408566,17.006234,0.097130
3,Low Value,434,2182.543779,2166.851032,15.693073,0.103461

In [22]:
# porcentaje de clientes por segmento
segment_summary["customer_percentage"] = (
    segment_summary["customers"] / len(df) * 100
)

In [23]:
# identificamos canal principal
segment_channel = (
    df.groupby(["customer_segment", "channel"])
    .size()
    .reset_index(name="customers")
)

segment_channel["percentage"] = (
    segment_channel.groupby("customer_segment")["customers"]
    .transform(lambda x: x / x.sum() * 100)
)

segment_channel

                   customer_segment           channel  customers  percentage
0  Cost Efficient - Potential Value   email marketing        166  100.000000
1      High Value - High Efficiency   email marketing         48  100.000000
2  High Value - Standard Efficiency  paid advertising         57   37.500000
3  High Value - Standard Efficiency          referral         47   30.921053
4  High Value - Standard Efficiency      social media         48   31.578947
5                         Low Value  paid advertising        137   31.566820
6                         Low Value          referral        160   36.866359
7                         Low Value      social media        137   31.566820

**CONCLUSIONES**

Con base al analisis de los diferentes canales y la categorizacion de segmento de clientes tenemos: 

1. High Value - High Efficiency (6%) 

- Priorizar la retencion de este segmento, son clientes que generan ingresos elevados a la empresa con un bajo costo. 
- Priorizar programas de fidelización de acuerdo a una identificacion de sus perfiles comerciales. 
- Incentivar la compra conjunta de otros productos (cross-selling) y ofrecer mejoras en los servicios que actualmente tiene (upselling)
- Crear ofertas personalizadas, esto a traves de diferentes medios, con el fin de sentirse especiales y de importancia para la compañia. 
- Ofrecer un canal exclusivo de comunicacion esto permite mejorar la experiencia en el servicio.

2. High Value - Standard Efficiency (19%)

- Analizar qué características de las campañas de Referral y Social Media permiten generar clientes High Value con costos considerablemente menores y utilizar estos aprendizajes para optimizar Paid Advertising.
- mejorar su eficiencia manteniendo el alto valor de los clientes obtenidos.

3. Cost Efficient - Potential Value (21%)

- Generar campañas de Cross-selling Up-selling.
- Identificar y entregar recomendaciones personalizadas.
- Realizar Campañas basadas en comportamiento de compra.
- Incentivos para aumentar frecuencia o valor de compra.

4. Low Value (54%)
- Identificar clientes con potencial de crecimiento es decir: 
    * Clientes con revenue cercano al percentil 75 ($ 3.824 )
    * Clientes con buena conversion
    * Identificar aquellos clientes que vengan de canales eficientes (alto revenue - bajo costo )
    * Identificar aquellos clientes con potencial de realizar cross-selling.